### ISSUE TITLE
Fatal error when starting

### ISSUE THREAD

**Issue by Falci** [imperviousinc/fingertip#29] opened 2022-10-24 09:35 UTC
When I open the Fingertip app, I got the following message:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/1330573/197495884-32b79874-d607-4dfb-898e-29e666034ed2.png">

macOS Monterey (M1)

**Comment by buffrr** [comment] 2022-10-24 14:35
Duplicate of #11. Please reopen if that doesn't resolve your issue. Thanks!

**Closed by buffrr** 2022-10-24 14:35 UTC
